In [28]:
import numpy as np
from scipy.linalg import eigh
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
np.set_printoptions(precision=4, suppress=True)  # 4 decimal places, no scientific notation

In [29]:
x1 = np.array([[1],[2]])
x2 = np.array([[2],[3]])
x3 = np.array([[3],[4]])    
x4 = np.array([[4],[5]])
X=np.concatenate((x1,x2,x3,x4), axis=1).T
print(X)

[[1 2]
 [2 3]
 [3 4]
 [4 5]]


In [30]:
sq_dist = np.sum((X[:,np.newaxis,:]- X[np.newaxis,:,:]).T**2,axis=0)
print(sq_dist)
sigma = 1.0
A = np.exp(-sq_dist / (2 * sigma**2))
D = np.diag(np.sum(A, axis=1))
L = D - A
print("Similarity Matrix A:\n", np.round(A, 4))
print("Degree Matrix D:\n", np.round(D, 4))
print("Laplacian Matrix L:\n", np.round(L, 4))

[[ 0  2  8 18]
 [ 2  0  2  8]
 [ 8  2  0  2]
 [18  8  2  0]]
Similarity Matrix A:
 [[1.     0.3679 0.0183 0.0001]
 [0.3679 1.     0.3679 0.0183]
 [0.0183 0.3679 1.     0.3679]
 [0.0001 0.0183 0.3679 1.    ]]
Degree Matrix D:
 [[1.3863 0.     0.     0.    ]
 [0.     1.7541 0.     0.    ]
 [0.     0.     1.7541 0.    ]
 [0.     0.     0.     1.3863]]
Laplacian Matrix L:
 [[ 0.3863 -0.3679 -0.0183 -0.0001]
 [-0.3679  0.7541 -0.3679 -0.0183]
 [-0.0183 -0.3679  0.7541 -0.3679]
 [-0.0001 -0.0183 -0.3679  0.3863]]


In [31]:
eval, evec = eigh(L)
print("Eigenvalues:\n", np.round(eval, 4))
print("Eigenvectors:\n", np.round(evec, 4))

Eigenvalues:
 [0.     0.2468 0.7724 1.2616]
Eigenvectors:
 [[ 0.5     0.6567  0.5    -0.2623]
 [ 0.5     0.2623 -0.5     0.6567]
 [ 0.5    -0.2623 -0.5    -0.6567]
 [ 0.5    -0.6567  0.5     0.2623]]
