In [1]:
import numpy as np
from scipy.linalg import eigh
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
# np.set_printoptions(precision=4, suppress=True)  # 4 decimal places, no scientific notation

In [2]:
x1 = np.array([[1],[2]])
x2 = np.array([[2],[3]])
x3 = np.array([[3],[4]])    
x4 = np.array([[5],[6]])
X=np.concatenate((x1,x2,x3,x4),axis=1)
print(X.shape)

(2, 4)


In [3]:
sq_dist = np.sum(X**2, axis=0)[:, np.newaxis] + np.sum(X**2, axis=0)[np.newaxis, :] - 2 * np.dot(X.T, X)
sigma = 1.0
A = np.exp(-sq_dist / (2 * sigma**2))
D = np.diag(np.sum(A, axis=1))
L = D - A
print("Similarity Matrix A:\n", np.round(A, 4))
print("Degree Matrix D:\n", np.round(D, 4))
print("Laplacian Matrix L:\n", np.round(L, 4))

Similarity Matrix A:
 [[1.000e+00 3.679e-01 1.830e-02 0.000e+00]
 [3.679e-01 1.000e+00 3.679e-01 1.000e-04]
 [1.830e-02 3.679e-01 1.000e+00 1.830e-02]
 [0.000e+00 1.000e-04 1.830e-02 1.000e+00]]
Degree Matrix D:
 [[1.3862 0.     0.     0.    ]
 [0.     1.7359 0.     0.    ]
 [0.     0.     1.4045 0.    ]
 [0.     0.     0.     1.0184]]
Laplacian Matrix L:
 [[ 3.862e-01 -3.679e-01 -1.830e-02 -0.000e+00]
 [-3.679e-01  7.359e-01 -3.679e-01 -1.000e-04]
 [-1.830e-02 -3.679e-01  4.045e-01 -1.830e-02]
 [-0.000e+00 -1.000e-04 -1.830e-02  1.840e-02]]


In [4]:
eval, evec = eigh(L)
print("Eigenvalues:\n", np.round(eval, 4))
print("Eigenvectors:\n", np.round(evec, 4))

Eigenvalues:
 [0.     0.0239 0.4142 1.1069]
Eigenvectors:
 [[ 0.5    -0.3124  0.6989  0.405 ]
 [ 0.5    -0.2947 -0.0176 -0.8141]
 [ 0.5    -0.2583 -0.7143  0.416 ]
 [ 0.5     0.8654  0.0331 -0.0069]]
