### Imports

In [1]:
import numpy as np

### Data

In [27]:
X = np.array([[-2 , -2 , -1 , 1 , 1 , 2 , 3 , 3],[-1 , 2 , 1 , 2 , 1 , 3 , 3 , 2]]).T
Y = np.array([[+1 , +1 , +1 , -1 , -1 , +1 , -1 , -1]]).T
print(f"X matrix:\n{X}")
print(f"Y matrix:\n{Y}")
print(X.shape)
print(Y.shape)
print(np.diag(Y.reshape(8,)))

X matrix:
[[-2 -1]
 [-2  2]
 [-1  1]
 [ 1  2]
 [ 1  1]
 [ 2  3]
 [ 3  3]
 [ 3  2]]
Y matrix:
[[ 1]
 [ 1]
 [ 1]
 [-1]
 [-1]
 [ 1]
 [-1]
 [-1]]
(8, 2)
(8, 1)
[[ 1  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0]
 [ 0  0  0 -1  0  0  0  0]
 [ 0  0  0  0 -1  0  0  0]
 [ 0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  0 -1  0]
 [ 0  0  0  0  0  0  0 -1]]


In [43]:
W = np.array([[0, 0]]).T
print(W.shape)
print(f"Weights W:\n{W}")
for i in range(1):
    vec = np.log(1+np.exp(-np.diag(Y.reshape(8,)) @ X @ W))
    # print(f"Vectorized loss values:\n{vec}")    
    Loss = np.sum(vec)
    d_Loss = - ((np.diag(Y.reshape(8,)) @ X).T @ (1/(1+np.exp(np.diag(Y.reshape(8,)) @ X @ W))))
    W = W - 1 * d_Loss
    print(f"Epoch:{i} Loss value:{Loss}")
print(f"Gradient of Loss:\n{d_Loss}")
print(f"Updated Weights W:\n{W}")


(2, 1)
Weights W:
[[0]
 [0]]
Epoch:0 Loss value:5.545177444479562
Gradient of Loss:
[[5.5]
 [1.5]]
Updated Weights W:
[[-5.5]
 [-1.5]]
