In [1]:
# Unnormalized spectral clustering example
# {a,b,c} fully connected and {d,e,f} fully connected (no edges between the two triples)

import numpy as np
from scipy.linalg import eigh
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

Input: Similarity matrix S ∈ R^{n×n}, number k of clusters to construct.

Construct a similarity graph. Let W be its weighted adjacency matrix.

In [13]:
# Vertices
names = ['a','b','c','d','e','f']

# Input: Adjacency matrix shape(nxn)
# W = np.array([
#     [0,1,1,0,0,0],
#     [1,0,1,0,0,0],
#     [1,1,0,0,0,0],
#     [0,0,1,0,1,1],
#     [0,0,0,1,0,1],
#     [0,0,0,1,1,0]
# ], dtype=float)
# W = np.array([
#     [0,1,0,0,0,0],
#     [1,0,0,0,0,0],
#     [0,0,0,1,0,0],
#     [0,0,1,0,0,0],
#     [0,0,0,0,0,1],
#     [0,0,0,0,1,0]
# ], dtype=float)
W = np.array([
    [0,1,1,0,0,0],
    [1,0,1,0,0,0],
    [1,1,0,1,0,0],
    [0,0,1,0,1,1],
    [0,0,0,1,0,1],
    [0,0,0,1,1,0]
], dtype=float)

n = W.shape[0]

Compute the unnormalized Laplacian L.

In [14]:
# Compute Degree matrix
D = np.diag(W.sum(axis=1))
print(D)


[[2. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 2. 0.]
 [0. 0. 0. 0. 0. 2.]]


In [15]:
# Compute the unnormalized Laplacian L
L = D - W
print(L)

[[ 2. -1. -1.  0.  0.  0.]
 [-1.  2. -1.  0.  0.  0.]
 [-1. -1.  3. -1.  0.  0.]
 [ 0.  0. -1.  3. -1. -1.]
 [ 0.  0.  0. -1.  2. -1.]
 [ 0.  0.  0. -1. -1.  2.]]


Compute the first k eigenvectors u1, . . . , uk of L.

In [16]:

# Compute eigenvalues and eigenvectors of L
# eigh returns eigenvalues in ascending order
eigvals, eigvecs = eigh(L)

print("Eigen values: ", np.round(eigvals, 4))


Eigen values:  [0.     0.4384 3.     3.     3.     4.5616]


In [17]:
np.round(eigvecs,3)

array([[-0.408,  0.465,  0.764,  0.   ,  0.   ,  0.185],
       [-0.408,  0.465, -0.546, -0.535, -0.   ,  0.185],
       [-0.408,  0.261, -0.218,  0.535,  0.   , -0.657],
       [-0.408, -0.261, -0.218,  0.535,  0.   ,  0.657],
       [-0.408, -0.465,  0.109, -0.267, -0.707, -0.185],
       [-0.408, -0.465,  0.109, -0.267,  0.707, -0.185]])

In [24]:
k = 2 # number of clusters

# Take the first k eigenvectors corresponding to smallest eigenvalues of L
U = eigvecs[:, :k]   # shape (n, k)

For i = 1, . . . , n, let y_i ∈ R^k be the vector corresponding to the i-th row of U

In [25]:
# Rows of U are the embedded points y_i in R^k
Y = U.copy()

In [26]:
Y

array([[-0.40824829,  0.46470513],
       [-0.40824829,  0.46470513],
       [-0.40824829,  0.26095647],
       [-0.40824829, -0.26095647],
       [-0.40824829, -0.46470513],
       [-0.40824829, -0.46470513]])

Cluster the points (yi)i=1,...,n in R^k with the k-means algorithm into clusters C1, . . . , Ck

In [27]:
# Run k-means on the rows of U
km = KMeans(n_clusters=k, n_init=50, random_state=42)
labels = km.fit_predict(Y)

In [28]:
labels

array([0, 0, 0, 1, 1, 1], dtype=int32)

In [29]:
# Collect clusters
clusters = {i: [] for i in range(k)}
for idx, l in enumerate(labels):
    clusters[l].append(names[idx])

print('Clusters')
for lab, verts in clusters.items():
    print(f'  Cluster {lab}: {verts}')

Clusters
  Cluster 0: ['a', 'b', 'c']
  Cluster 1: ['d', 'e', 'f']
